### ISSUE TITLE
Bad Attribute

### ISSUE THREAD

**Issue by melih** [dmryakup/instapy#1]
The console outputs the following lines when executed.
```
DevTools listening on ws://127.0.0.1:49416/devtools/browser/cebf5f05-45d6-4186-b
14c-6322ec9089bc
[1013/192552.901:ERROR:gl_surface_egl.cc(767)] EGL Driver message (Error) eglQue
ryDeviceAttribEXT: Bad attribute.
Takipten çıkarma işlemi başladı
Traceback (most recent call last):
  File "{Path}\takiptençıkmabotu.py", line 62, in <module>
    browser.execute_script("arguments[0].click();", buttons[unfollow])
IndexError: list index out of range
[1013/192656.661:ERROR:gl_surface_egl.cc(767)] EGL Driver message (Error) eglQue
ryDeviceAttribEXT: Bad attribute.
...
```
https://github.com/dmryakup/instapy/blob/ec5491037e62ce4d44e456fec3eb662b0fbb1a2d/takipten%C3%A7%C4%B1kmabotu.py#L62

**Comment by dmryakup** [comment]
Hi.

I created a new bot. And hope that it will be more dynamic. U can follow
the link to access.

https://github.com/dmryakup/instagramfullbot

And I am working on a user interface for the bot. You can try it too..

Have a nice day...

Melih Erkin Sarıçam <notifications@github.com>, 13 Eki 2020 Sal, 19:31
tarihinde şunu yazdı:

**Comment by melih** [comment]
Great. I'll try to contribute, too.
